version: "3.1"
services:
  # The Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autograder
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  # The Queue
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
